
Go to runForLoopCalculatePerformanceLearnsLeakyRateESNBothTasksCOIL100 ,
runForLoopCalculatePerformanceLearnsLeakyRateESNBothTasksMIRO,
runForLoopCalculatePerformanceLearnsLeakyRateESNBothTasksMIROFinegrain
to recreate figures of the ESN experiment.
